# Generated by Django 5.0.3 on 2024-03-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donateblood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('bloodGroup', models.CharField(max_length=50)),
                ('contactNumber', models.CharField(max_length=10)),
            ],
        ),
    ]
