# Generated by Django 5.0.3 on 2024-03-24 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_donateblood_bloodgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donateblood',
            name='date',
            field=models.DateField(),
        ),
    ]
