# Generated by Django 5.0.3 on 2024-03-24 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_register'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Register',
            new_name='Registering',
        ),
    ]
