# Generated by Django 5.0.3 on 2024-03-25 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_register_registering'),
    ]

    operations = [
        migrations.AddField(
            model_name='registering',
            name='re_password',
            field=models.CharField(default='', max_length=50),
        ),
    ]
