# Generated by Django 5.0.3 on 2024-03-25 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_registering_re_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registering',
            new_name='register',
        ),
    ]
