# Generated by Django 5.0.3 on 2024-03-26 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_delete_register_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='requestBlood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('bloodGroup', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B-', 'B-'), ('B-', 'B+'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O-', 'O-'), ('O+', 'O+')], max_length=50)),
                ('contactNumber', models.CharField(max_length=10)),
                ('quantity', models.CharField(max_length=50)),
                ('urgency', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=50)),
            ],
        ),
    ]
